name: Scrapper web

on:
  schedule:
    # Se ejecuta automáticamente cada 3 horas (minuto 0)
    - cron: '0 */3 * * *'
  # Mantiene la opción de ejecutarlo manualmente cuando quieras
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./scrapper

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install playwright beautifulsoup4 gspread google-auth pandas openpyxl
          playwright install chromium
          playwright install-deps

      - name: Ejecutar script de MITV_Clasica
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        run: python MITV_Clasica.py

      - name: Ejecutar script de CN City
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        run: python cncity.py

      - name: Ejecutar script de retroblast
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        run: python retroblast.py

      - name: Ejecutar script de Janimotion
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        run: python janimotion.py

      - name: Ejecutar script de Doble C
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        run: python doblec.py
        





        
